"""Initial migration: usuarios, productos, carritos, items_carrito

Revision ID: 0f02e2716db6
Revises: 
Create Date: 2025-11-06 23:51:30.543502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f02e2716db6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productos',
    sa.Column('id_producto', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('imagen', sa.Text(), nullable=True),
    sa.Column('rating_rate', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('rating_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('precio > 0', name='ck_productos_precio_positivo'),
    sa.CheckConstraint('rating_count >= 0', name='ck_productos_rating_count_no_negativo'),
    sa.CheckConstraint('rating_rate IS NULL OR (rating_rate >= 0 AND rating_rate <= 5)', name='ck_productos_rating_range'),
    sa.CheckConstraint('stock >= 0', name='ck_productos_stock_no_negativo'),
    sa.PrimaryKeyConstraint('id_producto')
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_productos_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_productos_id_producto'), ['id_producto'], unique=False)
        batch_op.create_index(batch_op.f('ix_productos_is_active'), ['is_active'], unique=False)

    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('apellido', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_usuarios_id_usuario'), ['id_usuario'], unique=False)
        batch_op.create_index(batch_op.f('ix_usuarios_is_active'), ['is_active'], unique=False)

    op.create_table('carritos',
    sa.Column('id_carrito', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('impuesto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('envio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_carrito')
    )
    with op.batch_alter_table('carritos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_carritos_id_carrito'), ['id_carrito'], unique=False)
        batch_op.create_index(batch_op.f('ix_carritos_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_carritos_usuario_id'), ['usuario_id'], unique=False)
        batch_op.create_index('ux_carritos_usuario_activo', ['usuario_id'], unique=True, postgresql_where=sa.text('is_active = 1'))

    op.create_table('items_carrito',
    sa.Column('id_item', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('carrito_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('cantidad >= 1', name='ck_items_cantidad_positiva'),
    sa.CheckConstraint('precio_unitario >= 0', name='ck_items_precio_no_negativo'),
    sa.CheckConstraint('subtotal >= 0', name='ck_items_subtotal_no_negativo'),
    sa.ForeignKeyConstraint(['carrito_id'], ['carritos.id_carrito'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id_producto'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_item'),
    sa.UniqueConstraint('carrito_id', 'producto_id', name='ux_items_carrito_producto')
    )
    with op.batch_alter_table('items_carrito', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_items_carrito_carrito_id'), ['carrito_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_carrito_id_item'), ['id_item'], unique=False)
        batch_op.create_index(batch_op.f('ix_items_carrito_producto_id'), ['producto_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items_carrito', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_items_carrito_producto_id'))
        batch_op.drop_index(batch_op.f('ix_items_carrito_id_item'))
        batch_op.drop_index(batch_op.f('ix_items_carrito_carrito_id'))

    op.drop_table('items_carrito')
    with op.batch_alter_table('carritos', schema=None) as batch_op:
        batch_op.drop_index('ux_carritos_usuario_activo', postgresql_where=sa.text('is_active = 1'))
        batch_op.drop_index(batch_op.f('ix_carritos_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_carritos_is_active'))
        batch_op.drop_index(batch_op.f('ix_carritos_id_carrito'))

    op.drop_table('carritos')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_is_active'))
        batch_op.drop_index(batch_op.f('ix_usuarios_id_usuario'))
        batch_op.drop_index(batch_op.f('ix_usuarios_email'))

    op.drop_table('usuarios')
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productos_is_active'))
        batch_op.drop_index(batch_op.f('ix_productos_id_producto'))
        batch_op.drop_index(batch_op.f('ix_productos_categoria'))

    op.drop_table('productos')
    # ### end Alembic commands ###
