"""Add user profiles, sales, ratings, favorites and seller functionality

Revision ID: 6decab79b444
Revises: 0f02e2716db6
Create Date: 2025-11-19 14:28:28.898258

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6decab79b444'
down_revision = '0f02e2716db6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfiles_usuario',
    sa.Column('id_perfil', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('foto_perfil', sa.Text(), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion_completa', sa.Text(), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('codigo_postal', sa.String(length=20), nullable=True),
    sa.Column('biografia', sa.Text(), nullable=True),
    sa.Column('es_vendedor', sa.Boolean(), nullable=False),
    sa.Column('calificacion_vendedor', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('total_ventas', sa.Integer(), nullable=False),
    sa.Column('fecha_nacimiento', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_perfil'),
    sa.UniqueConstraint('usuario_id')
    )
    with op.batch_alter_table('perfiles_usuario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_perfiles_usuario_id_perfil'), ['id_perfil'], unique=False)

    op.create_table('favoritos',
    sa.Column('id_favorito', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id_producto'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_favorito'),
    sa.UniqueConstraint('usuario_id', 'producto_id', name='uq_usuario_producto')
    )
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favoritos_id_favorito'), ['id_favorito'], unique=False)
        batch_op.create_index(batch_op.f('ix_favoritos_producto_id'), ['producto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favoritos_usuario_id'), ['usuario_id'], unique=False)

    op.create_table('ventas',
    sa.Column('id_venta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comprador_id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('precio_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('comision_plataforma', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado_venta', sa.Enum('PENDIENTE', 'PAGADO', 'ENVIADO', 'COMPLETADO', 'CANCELADO', name='estadoventa'), nullable=False),
    sa.Column('metodo_pago', sa.String(length=50), nullable=True),
    sa.Column('fecha_venta', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_entrega_estimada', sa.DateTime(), nullable=True),
    sa.Column('fecha_entrega_real', sa.DateTime(), nullable=True),
    sa.Column('calificacion_comprador', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['comprador_id'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id_producto'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vendedor_id'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_venta')
    )
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ventas_comprador_id'), ['comprador_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ventas_estado_venta'), ['estado_venta'], unique=False)
        batch_op.create_index(batch_op.f('ix_ventas_id_venta'), ['id_venta'], unique=False)
        batch_op.create_index(batch_op.f('ix_ventas_producto_id'), ['producto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ventas_vendedor_id'), ['vendedor_id'], unique=False)

    op.create_table('valoraciones',
    sa.Column('id_valoracion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('venta_id', sa.Integer(), nullable=False),
    sa.Column('evaluador_id', sa.Integer(), nullable=False),
    sa.Column('evaluado_id', sa.Integer(), nullable=False),
    sa.Column('tipo_evaluacion', sa.Enum('VENDEDOR', 'COMPRADOR', name='tipoevaluacion'), nullable=False),
    sa.Column('calificacion', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('calificacion >= 1 AND calificacion <= 5', name='ck_valoracion_rango'),
    sa.ForeignKeyConstraint(['evaluado_id'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evaluador_id'], ['usuarios.id_usuario'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venta_id'], ['ventas.id_venta'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_valoracion')
    )
    with op.batch_alter_table('valoraciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_valoraciones_evaluado_id'), ['evaluado_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_valoraciones_evaluador_id'), ['evaluador_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_valoraciones_id_valoracion'), ['id_valoracion'], unique=False)
        batch_op.create_index(batch_op.f('ix_valoraciones_venta_id'), ['venta_id'], unique=False)

    with op.batch_alter_table('carritos', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)

    with op.batch_alter_table('items_carrito', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendedor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('estado_producto', sa.Enum('DISPONIBLE', 'VENDIDO', 'PAUSADO', 'ELIMINADO', name='estadoproducto'), nullable=False))
        batch_op.add_column(sa.Column('condicion', sa.Enum('NUEVO', 'USADO', 'REACONDICIONADO', name='condicionproducto'), nullable=False))
        batch_op.alter_column('precio',
               existing_type=mysql.DECIMAL(precision=10, scale=2),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_productos_estado_producto'), ['estado_producto'], unique=False)
        batch_op.create_index(batch_op.f('ix_productos_vendedor_id'), ['vendedor_id'], unique=False)
        batch_op.create_foreign_key(None, 'usuarios', ['vendedor_id'], ['id_usuario'], ondelete='CASCADE')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_productos_vendedor_id'))
        batch_op.drop_index(batch_op.f('ix_productos_estado_producto'))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
        batch_op.alter_column('precio',
               existing_type=sa.Integer(),
               type_=mysql.DECIMAL(precision=10, scale=2),
               existing_nullable=False)
        batch_op.drop_column('condicion')
        batch_op.drop_column('estado_producto')
        batch_op.drop_column('vendedor_id')

    with op.batch_alter_table('items_carrito', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)

    with op.batch_alter_table('carritos', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)

    with op.batch_alter_table('valoraciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_valoraciones_venta_id'))
        batch_op.drop_index(batch_op.f('ix_valoraciones_id_valoracion'))
        batch_op.drop_index(batch_op.f('ix_valoraciones_evaluador_id'))
        batch_op.drop_index(batch_op.f('ix_valoraciones_evaluado_id'))

    op.drop_table('valoraciones')
    with op.batch_alter_table('ventas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ventas_vendedor_id'))
        batch_op.drop_index(batch_op.f('ix_ventas_producto_id'))
        batch_op.drop_index(batch_op.f('ix_ventas_id_venta'))
        batch_op.drop_index(batch_op.f('ix_ventas_estado_venta'))
        batch_op.drop_index(batch_op.f('ix_ventas_comprador_id'))

    op.drop_table('ventas')
    with op.batch_alter_table('favoritos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favoritos_usuario_id'))
        batch_op.drop_index(batch_op.f('ix_favoritos_producto_id'))
        batch_op.drop_index(batch_op.f('ix_favoritos_id_favorito'))

    op.drop_table('favoritos')
    with op.batch_alter_table('perfiles_usuario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_perfiles_usuario_id_perfil'))

    op.drop_table('perfiles_usuario')
    # ### end Alembic commands ###
